# -*- coding: utf-8 -*-
"""Week4-A108060032-林品慰.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FYZgxzzblgdaAs5SVCATV-IxGrGBF7z
"""



print("Hello  World")
print(1+1)